### ISSUE TITLE
Consider camelizing colour keys

### ISSUE THREAD

**Issue by destructobeam** [tachyons-css/tachyons-styled-react#1]
Looking interesting, I was starting on a conversion util for tachyons for css-in-is before losing all my free time.

Anyway...

Would you possibly consider using camelized keys for colour values so they can be usable via dot-notation?

**Comment by mrmrs** [comment]
Great question. My original intent here is to port over tachyons css as closely as possible. So I wanted to keep the class names the same in the event someone was already familiar with them. My longer term plan is that themes should be easy to swap in and out and there could be a variety of themes to choose from. I personally prefer arrays separated by hues for my color palette and really enjoy using dot syntax. Styled-system supports this out of the box so if you customize the theme yourself it should work straight away.
